name: Test CI pull request event

on:
 pull_request: #jika terdapat pull request, bisa juga on push #push
  branches: #ke branch
   - master #master, jadi bisa branch lain

jobs: #maka jalanin jobs ini
 test: #ini namanya bebas, idnya, jalaninnya paralel kalo utk jenis ini
  name: percobaan fase test #nama idnya
  runs-on: ubuntu-latest #ini jalanin perintahnya pake apa, jadi bisa pake bash
  steps: #kalo step itu sequence jalannya
  - name: Check out the repo #ini buat ngepull request yg dari branch terbaru
    uses: actions/checkout@v2

  - name: Exec shell
    run: |#di sini bisa jalanin perintah bash
     id
     ls -lah
     uname -a
     echo "ini testing"

 test2:
  name: test kedua
  runs-on: ubuntu-latest
  steps:
  - name: Pull branch
    uses: actions/checkout@v2

  - name: see calendar
    run: |
     cal
     cat notes.md
     ls
     echo "ini gak di pull request"

 check-git-status:
  name: git status
  runs-on: ubuntu-latest
  steps:
  - name: Pull Request branch github-cicd
    uses: actions/checkout@v2

  - name: git status
    run: git status

  - name: test password secret
    run: echo ${{ secrets.MY_PASSWORD }}
